pkg_dnf = {
    "autoconf": {},
    "automake": {},
    "bison": {},
    "byacc": {},
    "cscope": {},
    "ctags": {},
    "diffstat": {},
    "doxygen": {},
    "doxygen": {},
    "elfutils": {},
    "flex": {},
    "gcc": {},
    "gcc-c++": {},
    "gcc-gfortran": {},
    "indent": {},
    "intltool": {},
    "libtool": {},
    "patchutils": {},
    "rcs": {},
    "redhat-rpm-config": {},
    "rpm-build": {},
    "rpm-sign": {},
    "swig": {},
    "systemtap": {},
}
