pkg_dnf = {
    'autoconf': {},
    'automake': {},
    'bison': {},
    'byacc': {},
    'clang': {},
    'cscope': {},
    'ctags': {},
    'diffstat': {},
    'doxygen': {},
    'doxygen': {},
    'elfutils': {},
    'flex': {},
    'gcc-gfortran': {},
    'indent': {},
    'intltool': {},
    'libtool': {},
    'patchutils': {},
    'rcs': {},
    'rpm-build': {},
    'rpm-sign': {},
    'swig': {},
    'systemtap': {},
}
